name: Build Docker

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - dockerfile
      - requirements.txt
      - setup.py
      - .github/workflows/docker.yml
      - pipelines/**/**.py

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:."
        push: true
        tags: marcelndeffo/builds:datasets
